---
- hosts: all
  become: yes
  tasks:
    - name: install apache2 and php package
      apt:
        name:
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]
 
    - name: install httpd and php package
      yum:
        name:
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest
        update_cache: yes 
      when: ansible_distribution in ["CentOS", "RedHat"]  
