- name: Install Cockpit
  hosts: gcloud-vm
  gather_facts: yes
  become: yes

  tasks:
    - name: install Cockpit
      shell: "apt install -t {{ ansible_distribution_release }}-backports cockpit -y"
