- hosts: k8s-master
  name: fetch kubeconfig file
  gather_facts: true
  become: yes
  tasks:
    - name: fetch kubeconfig file
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig
        flat: yes
      # when: ansible_hostname == "k8s-master"
