- hosts: k8s_master
  name: fetch kubeconfig file
  gather_facts: false
  become: yes
  tasks:
    - name: fetch kubeconfig file
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig
        flat: yes
