- name: Deploy trang web dau tien
  hosts: local
  become: yes
  vars:
    my_name: "Tran Thanh Dat"
  tasks:
    - name: update package
      apt:
        update_cache: yes
      ignore_errors: yes
    - name: Cai dat Nginx
      apt:
        name: nginx
        state: absent
    - name: Tao file index.html cho website
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: "0644" # Set quyen file (optional)
    - name: Thong bao hoan tat
      debug:
        msg: "File index.html da duoc tao tai thu muc hien tai!"
